language: cpp
cache: apt
matrix:
   # =======================================================
   # DEBUG Build
   # =======================================================
   # D1. clang-mp-4.8     | DEBUG    
   - CMAKE_CXX_COMPILER=clang-mp-3.4
     CMAKE_BUILD_TYPE=DEBUG
   # D2. g++-mp-4.8     | DEBUG    
   - CMAKE_CXX_COMPILER=g++-mp-4.8
     CMAKE_BUILD_TYPE=DEBUG
   # =======================================================
   # RELEASE Build
   # =======================================================
   # D1. clang-mp-4.8     | RELEASE   
   - CMAKE_CXX_COMPILER=clang-mp-3.4
     CMAKE_BUILD_TYPE=RELEASE
   # D2. g++-mp-4.8     | RELEASE    
   - CMAKE_CXX_COMPILER=g++-mp-4.8
     CMAKE_BUILD_TYPE=RELEASE
   

script:
  - mkdir -p build
  - cd build
  - GENERATOR=-GNinja;
  - /usr/bin/cmake -DIGNORE_SORRY=ON  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} ${GENERATOR} -DCMAKE_PROGRAM_PATH=/usr/bin ../
  - cd ..
after_script:
  - cd build
  - ninja -j 1
  - cd ..

os:
  - linux
  - osx

notifications:
  email:
    recipients:
     - seahorn-build@googlegroups.com
    on_success: always
    on_failure: always